# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0df22b2795665f3210c0cf8f3e6b4f1dc98f798a7ee01b2d04601ca1173d42a57138b224400af687251a74ef9448c8921e73531cd35e656ef543fb1c7be6f443

test:
  secret_key_base: bd5ae40a8c6aefe0dd3f2bff9b5afa6535115512f98c71cec58958749ba593475be9f60a9cc13ad2b7eb44d344782f31f1226649f04c84d6abb10083152c6903

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
